[tool.ruff]
exclude = [
    ".bandit",
    ".git",
    "api.py",
    ".ipynb_checkpoints",
    "setup.py",
]
ignore = [
    "C901",
    "D100",
    "D103",
    "D104",
    "D202",
    "E501",
    "D"
]
line-length = 99
select = [
    "C9",
    # "D",
    "E",
    "F",
    "W",
]

# [tool.ruff.mccabe]
# max-complexity = 12

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.ruff.per-file-ignores]
"src/query_insights/api.py" = ["F401"]
"src/query_insights/post_processing.py" = ["W605"]