name: Function_app

on:
  push:
    branches:
    - main
env:
  REGISTRY: 'demoacr2710.azurecr.io'                 # set this to proper value for REGISTRY
  NAMESPACE: 'demo-image'               # set this to proper value for NAMESPACE
  IMAGE: 'demo-image'                       # set this to proper value for IMAGE
  TAG: 'latest'



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'ACR Login'
      uses: azure/docker-login@v1
      with:
        login-server: demoacr2710.azurecr.io
        username: demoacr2710
        password: Vcic8zmTKdnaM3S6NuyxV5LtTeEoY5fd29+j6wY4qj+ACRCGC//O

    - name: 'Compose Customized Docker Image'
      shell: bash
      run: |
        # If your function app project is not located in your repository's root
        # Please change the path to your directory for docker build
        docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }} -f mle/Dockerfile
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}

    - name: 'Run Azure Functions Container Action'
      uses: Azure/functions-container-action@v1
      id: fa
      with:
        app-name: trial8787
        image: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}